/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.app;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author DevTARDE A
 */
public class JanelaCadClientes extends javax.swing.JFrame {

    /**
     * Creates new form JanelaCadClientes
     */
    public JanelaCadClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        JLabelCadClientes = new javax.swing.JLabel();
        JLabelIconImage = new javax.swing.JLabel();
        JTextFieldNome = new javax.swing.JTextField();
        JTextFieldTelefone = new javax.swing.JTextField();
        JTextFieldCpf = new javax.swing.JTextField();
        JRadioButtonFem = new javax.swing.JRadioButton();
        JRadioButtonMasc = new javax.swing.JRadioButton();
        JLabelSexo = new javax.swing.JLabel();
        JLabelNome = new javax.swing.JLabel();
        JLabelTelefone = new javax.swing.JLabel();
        JLabelCpf = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JTextFieldTelefone1 = new javax.swing.JTextField();
        JLabelTelefone1 = new javax.swing.JLabel();
        JTextFieldTelefone2 = new javax.swing.JTextField();
        JLabelTelefone2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        setMinimumSize(new java.awt.Dimension(830, 600));
        setName("Cadastro de Clientes"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(830, 600));
        setSize(new java.awt.Dimension(830, 600));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        JLabelCadClientes.setBackground(new java.awt.Color(102, 102, 102));
        JLabelCadClientes.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        JLabelCadClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelCadClientes.setLabelFor(this);
        JLabelCadClientes.setText("CADASTRO DE CLIENTES ");
        JLabelCadClientes.setAlignmentX(1.0F);
        JLabelCadClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JLabelCadClientes.setName("Cadclientes"); // NOI18N
        getContentPane().add(JLabelCadClientes);
        JLabelCadClientes.setBounds(180, 20, 483, 25);

        JLabelIconImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/app/icone-removebg-preview.png"))); // NOI18N
        JLabelIconImage.setPreferredSize(new java.awt.Dimension(200, 200));
        getContentPane().add(JLabelIconImage);
        JLabelIconImage.setBounds(40, 70, 100, 100);

        JTextFieldNome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(JTextFieldNome);
        JTextFieldNome.setBounds(190, 100, 150, 20);

        JTextFieldTelefone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(JTextFieldTelefone);
        JTextFieldTelefone.setBounds(570, 150, 150, 20);

        JTextFieldCpf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(JTextFieldCpf);
        JTextFieldCpf.setBounds(190, 150, 150, 20);

        JRadioButtonFem.setText("Feminino");
        JRadioButtonFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRadioButtonFemActionPerformed(evt);
            }
        });
        getContentPane().add(JRadioButtonFem);
        JRadioButtonFem.setBounds(460, 150, 73, 21);

        JRadioButtonMasc.setText("Masculino");
        JRadioButtonMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRadioButtonMascActionPerformed(evt);
            }
        });
        getContentPane().add(JRadioButtonMasc);
        JRadioButtonMasc.setBounds(380, 150, 78, 21);

        JLabelSexo.setText("Sexo: ");
        getContentPane().add(JLabelSexo);
        JLabelSexo.setBounds(380, 130, 37, 16);

        JLabelNome.setText("Nome:");
        getContentPane().add(JLabelNome);
        JLabelNome.setBounds(190, 80, 35, 16);

        JLabelTelefone.setText("Data do cadastro:");
        getContentPane().add(JLabelTelefone);
        JLabelTelefone.setBounds(570, 130, 110, 16);

        JLabelCpf.setText("CPF:");
        getContentPane().add(JLabelCpf);
        JLabelCpf.setBounds(190, 130, 23, 16);

        jPanel1.setBackground(java.awt.SystemColor.controlShadow);
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setToolTipText("");
        jPanel1.setComponentPopupMenu(jPopupMenu1);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 190, 790, 160);

        JTextFieldTelefone1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(JTextFieldTelefone1);
        JTextFieldTelefone1.setBounds(380, 100, 150, 20);

        JLabelTelefone1.setText("Telefone: ");
        getContentPane().add(JLabelTelefone1);
        JLabelTelefone1.setBounds(380, 80, 60, 16);

        JTextFieldTelefone2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(JTextFieldTelefone2);
        JTextFieldTelefone2.setBounds(570, 100, 150, 20);

        JLabelTelefone2.setText("Email:");
        getContentPane().add(JLabelTelefone2);
        JLabelTelefone2.setBounds(570, 80, 60, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JRadioButtonMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRadioButtonMascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRadioButtonMascActionPerformed

    private void JRadioButtonFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRadioButtonFemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRadioButtonFemActionPerformed

    private void JTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCadClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelCadClientes;
    private javax.swing.JLabel JLabelCpf;
    private javax.swing.JLabel JLabelIconImage;
    private javax.swing.JLabel JLabelNome;
    private javax.swing.JLabel JLabelSexo;
    private javax.swing.JLabel JLabelTelefone;
    private javax.swing.JLabel JLabelTelefone1;
    private javax.swing.JLabel JLabelTelefone2;
    private javax.swing.JRadioButton JRadioButtonFem;
    private javax.swing.JRadioButton JRadioButtonMasc;
    private javax.swing.JTextField JTextFieldCpf;
    private javax.swing.JTextField JTextFieldNome;
    private javax.swing.JTextField JTextFieldTelefone;
    private javax.swing.JTextField JTextFieldTelefone1;
    private javax.swing.JTextField JTextFieldTelefone2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
